name: MihomoKit CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up golang environment
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      
      - name: Set up gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile init
        
      - name: Build MihomoKit.xcframework
        run: |
          go mod download
          make
      
      - name: Zip MihomoKit.xcframework
        run: |
          zip -r MihomoKit.xcframework.zip target/MihomoKit.xcframework

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MihomoKit.xcframework
          path: MihomoKit.xcframework.zip
        